import type { Item } from '~/entities/items/model'

export const ITEMS_MOCKS: Item[] = [
  {
    id: 1,
    profileImg: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&h=600&fit=crop',
    title: 'Базовая футболка',
    type: "shirts",
    description: 'Классическая базовая футболка из хлопка',
    price: 2_500_00,
    characteristics: [
      'Материал: 100% хлопок',
      'Классический крой',
      'Короткие рукава',
      'Круглый вырез',
      'Машинная стирка',
    ],
    sizes: [{
      name: 'S',
      isAvailable: true,
      description: '160см - 168см',
    },
    {
      name: 'M',
      isAvailable: true,
      description: '168см - 176см',
    },
    {
      name: 'L',
      isAvailable: false,
      description: '176см - 184см',
    },
    {
      name: 'XL',
      isAvailable: true,
      description: '184см - 193см',
    }],
  },
  {
    id: 2,
    profileImg: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=400&h=600&fit=crop',
    title: 'Базовые брюки',
    type: "pants",
    description: 'Классические базовые брюки прямого кроя',
    price: 4_500_00,
    characteristics: [
      'Материал: хлопок с эластаном',
      'Прямой крой',
      'Классическая посадка',
      'Много карманов',
      'Пояс на резинке',
    ],
    sizes: [{
      name: '30',
      isAvailable: true,
      description: 'Талия 76см',
    },
    {
      name: '32',
      isAvailable: true,
      description: 'Талия 81см',
    },
    {
      name: '34',
      isAvailable: false,
      description: 'Талия 86см',
    },
    {
      name: '36',
      isAvailable: true,
      description: 'Талия 91см',
    }],
  },
  {
    id: 3,
    profileImg: 'https://cdn.prod.website-files.com/642d682a6e4ca0d303c81fdf/6458ec73fbcddebb5bd7e2dd_Polo%20T-shirt%20Mockup.webp',
    title: 'Поло классическое',
    type: "shirts",
    description: 'Элегантная футболка-поло для стильного образа',
    price: 3_200_00,
    characteristics: [
      'Материал: 100% хлопок',
      'Воротник-поло',
      'Планка с 3 пуговицами',
      'Короткие рукава',
      'Классический крой',
    ],
    sizes: [{
      name: 'S',
      isAvailable: true,
      description: '160см - 168см',
    },
    {
      name: 'M',
      isAvailable: true,
      description: '168см - 176см',
    },
    {
      name: 'L',
      isAvailable: true,
      description: '176см - 184см',
    },
    {
      name: 'XL',
      isAvailable: false,
      description: '184см - 193см',
    }],
  },
  {
    id: 4,
    profileImg: 'https://mockups-design-com.b-cdn.net/wp-content/uploads/2021/08/Apple_Watch_Mockup_2.jpg',
    title: 'Умные часы',
    type: "accessories",
    description: 'Минималистичные часы для повседневной носки',
    price: 8_900_00,
    characteristics: [
      'Материал корпуса: нержавеющая сталь',
      'Механизм: кварцевый',
      'Стекло: минеральное',
      'Водозащита: 50 метров',
      'Ремешок: кожаный',
    ],
    sizes: [{
      name: 'OneSize',
      isAvailable: true,
      description: 'Универсальный размер',
    }],
  },
  {
    id: 5,
    profileImg: 'https://dcdesire.com/cdn/shop/files/Untitled_design_-_2025-05-13T210229.540.png?v=1747162996',
    title: 'Пуховик демисезонный',
    type: "outerwear",
    description: 'Легкая куртка для прохладной погоды',
    price: 12_500_00,
    characteristics: [
      'Материал: нейлон с полиуретановым покрытием',
      'Утеплитель: синтепон',
      'Водоотталкивающая пропитка',
      'Застежка-молния с ветрозащитной планкой',
      'Два боковых кармана',
    ],
    sizes: [{
      name: 'M',
      isAvailable: true,
      description: '168см - 176см',
    },
    {
      name: 'L',
      isAvailable: true,
      description: '176см - 184см',
    },
    {
      name: 'XL',
      isAvailable: false,
      description: '184см - 193см',
    }],
  },
  {
    id: 6,
    profileImg: 'https://goodmockups.com/wp-content/uploads/2021/07/Free-Sleeveless-Women-Summer-Dress-Mockup-PSD-Set-1.jpg',
    title: 'Платье летнее',
    type: "skirts",
    description: 'Воздушное платье для теплых дней',
    price: 5_800_00,
    characteristics: [
      'Материал: вискоза',
      'Свободный силуэт',
      'Длина миди',
      'Рукава 3/4',
      'Принт: цветочный',
    ],
    sizes: [{
      name: 'XS',
      isAvailable: true,
      description: '40-42 размер',
    },
    {
      name: 'S',
      isAvailable: true,
      description: '42-44 размер',
    },
    {
      name: 'M',
      isAvailable: false,
      description: '44-46 размер',
    },
    {
      name: 'L',
      isAvailable: true,
      description: '46-48 размер',
    }],
  },
  {
    id: 7,
    profileImg: 'https://gitu.net/gituimg/free-psd-mockups-download/flying-sneakers-mockup.jpg',
    title: 'Кроссовки спортивные',
    type: "shoes",
    description: 'Удобные кроссовки для активного образа жизни',
    price: 7_500_00,
    characteristics: [
      'Верх: текстиль и синтетика',
      'Подошва: резина',
      'Технология амортизации',
      'Дышащая подкладка',
      'Шнуровка',
    ],
    sizes: [{
      name: '40',
      isAvailable: true,
      description: 'EU 40',
    },
    {
      name: '41',
      isAvailable: true,
      description: 'EU 41',
    },
    {
      name: '42',
      isAvailable: false,
      description: 'EU 42',
    },
    {
      name: '43',
      isAvailable: true,
      description: 'EU 43',
    },
    {
      name: '44',
      isAvailable: true,
      description: 'EU 44',
    }],
  },
  {
    id: 8,
    profileImg: 'https://images.rawpixel.com/image_800/cHJpdmF0ZS9sci9pbWFnZXMvd2Vic2l0ZS8yMDI0LTAxL3Jhd3BpeGVsX29mZmljZV8xOV9yZWFsX3Bob3RvX29mX2Ffc2Nob29sX2JhZ19pc29sYXRlZF9vbl9hX3doaV8wMWM0MzgyNy1hNzQzLTRlMTMtYTZlYi0zYmUyZmY2MGVkNmUtcm0xMTg3LW1vY2t1cF8xLmpwZw.jpg',
    title: 'Рюкзак городской',
    type: "accessories",
    description: 'Практичный рюкзак для города и путешествий',
    price: 4_200_00,
    characteristics: [
      'Материал: нейлон Oxford',
      'Объем: 20 литров',
      'Отделение для ноутбука 15"',
      'Водоотталкивающее покрытие',
      'Эргономичные лямки',
    ],
    sizes: [{
      name: 'OneSize',
      isAvailable: true,
      description: 'Универсальный размер',
    }],
  }
]