import type { Item } from '~/entities/items/model'

export const ITEMS_MOCKS: Item[] = [
  {
    id: 1,
    profileImg: 'https://m.media-amazon.com/images/I/71gEWlwpN9L._AC_SX569_.jpg',
    title: 'Худи 1',
    description: 'ПОЛОСА',
    price: 16_500_00,
  },
  {
    id: 1,
    profileImg: 'https://m.media-amazon.com/images/I/71gEWlwpN9L._AC_SX569_.jpg',
    title: 'Худи 2',
    description: '123123123',
    price: 16_500_00,
    characteristics: [
      'Утеплитель холофайбер уложенный в два слоя',
      'Температурный режим до –25°',
      'Ткань с пропиткой WR',
      'Съемный капюшон с магнитными застёжками',
      'Стропы для носки куртки в помещении',
    ],
    sizes: [{
      name: 'm',
      isAvailable: false,
      description: '168см - 176см',
    },
    {
      name: 'l',
      isAvailable: true,
      description: '176см - 184см',
    },
    {
      name: 'xl',
      isAvailable: true,
      description: '184см - 193см',
    }],
  },
  {
    id: 2,
    profileImg: 'https://m.media-amazon.com/images/I/71gEWlwpN9L._AC_SX569_.jpg',
    title: 'Худи 3',
    description: '123123123',
    price: 16_500_00,
    characteristics: [
      'Утеплитель холофайбер уложенный в два слоя',
      'Температурный режим до –25°',
      'Ткань с пропиткой WR',
      'Съемный капюшон с магнитными застёжками',
      'Стропы для носки куртки в помещении',
    ],
    sizes: [{
      name: 'm',
      isAvailable: false,
      description: '168см - 176см',
    },
    {
      name: 'l',
      isAvailable: true,
      description: '176см - 184см',
    },
    {
      name: 'xl',
      isAvailable: true,
      description: '184см - 193см',
    }],
  },
  {
    id: 1,
    profileImg: 'https://m.media-amazon.com/images/I/71gEWlwpN9L._AC_SX569_.jpg',
    title: 'Худи 4',
    description: '123123123',
    price: 16_500_00,
    characteristics: [
      'Утеплитель холофайбер уложенный в два слоя',
      'Температурный режим до –25°',
      'Ткань с пропиткой WR',
      'Съемный капюшон с магнитными застёжками',
      'Стропы для носки куртки в помещении',
    ],
    sizes: [{
      name: 'm',
      isAvailable: false,
      description: '168см - 176см',
    },
    {
      name: 'l',
      isAvailable: true,
      description: '176см - 184см',
    },
    {
      name: 'xl',
      isAvailable: true,
      description: '184см - 193см',
    }],
  },
  {
    id: 1,
    profileImg: 'https://m.media-amazon.com/images/I/71gEWlwpN9L._AC_SX569_.jpg',
    title: 'Худи 5',
    description: '123123123',
    price: 16_500_00,
    characteristics: [
      'Утеплитель холофайбер уложенный в два слоя',
      'Температурный режим до –25°',
      'Ткань с пропиткой WR',
      'Съемный капюшон с магнитными застёжками',
      'Стропы для носки куртки в помещении',
    ],
    sizes: [{
      name: 'm',
      isAvailable: false,
      description: '168см - 176см',
    },
    {
      name: 'l',
      isAvailable: true,
      description: '176см - 184см',
    },
    {
      name: 'xl',
      isAvailable: true,
      description: '184см - 193см',
    }],
  },
  {
    id: 1,
    profileImg: 'https://m.media-amazon.com/images/I/71gEWlwpN9L._AC_SX569_.jpg',
    title: 'Худи 1',
    description: 'ПОЛОСА',
    price: 16_500_00,
    characteristics: [
      'Утеплитель холофайбер уложенный в два слоя',
      'Температурный режим до –25°',
      'Ткань с пропиткой WR',
      'Съемный капюшон с магнитными застёжками',
      'Стропы для носки куртки в помещении',
    ],
    sizes: [{
      name: 'm',
      isAvailable: false,
      description: '168см - 176см',
    },
    {
      name: 'l',
      isAvailable: true,
      description: '176см - 184см',
    },
    {
      name: 'xl',
      isAvailable: true,
      description: '184см - 193см',
    }],
  },
  {
    id: 1,
    profileImg: 'https://m.media-amazon.com/images/I/71gEWlwpN9L._AC_SX569_.jpg',
    title: 'Худи 2',
    description: '123123123',
    price: 7_000_00,
    characteristics: [
      'Утеплитель холофайбер уложенный в два слоя',
      'Температурный режим до –25°',
      'Ткань с пропиткой WR',
      'Съемный капюшон с магнитными застёжками',
      'Стропы для носки куртки в помещении',
    ],
    sizes: [{
      name: 'm',
      isAvailable: false,
      description: '168см - 176см',
    },
    {
      name: 'l',
      isAvailable: true,
      description: '176см - 184см',
    },
    {
      name: 'xl',
      isAvailable: true,
      description: '184см - 193см',
    }],
  },
  {
    id: 3,
    profileImg: 'https://m.media-amazon.com/images/I/71gEWlwpN9L._AC_SX569_.jpg',
    title: 'Худи 3',
    description: '123123123',
    price: 8_000_00,
    characteristics: [
      'Утеплитель холофайбер уложенный в два слоя',
      'Температурный режим до –25°',
      'Ткань с пропиткой WR',
      'Съемный капюшон с магнитными застёжками',
      'Стропы для носки куртки в помещении',
    ],
    sizes: [{
      name: 'm',
      isAvailable: false,
      description: '168см - 176см',
    },
    {
      name: 'l',
      isAvailable: true,
      description: '176см - 184см',
    },
    {
      name: 'xl',
      isAvailable: true,
      description: '184см - 193см',
    }],
  },
  {
    id: 4,
    profileImg: 'https://m.media-amazon.com/images/I/71gEWlwpN9L._AC_SX569_.jpg',
    title: 'Худи 4',
    description: '123123123',
    price: 7_000_00,
    characteristics: [
      'Утеплитель холофайбер уложенный в два слоя',
      'Температурный режим до –25°',
      'Ткань с пропиткой WR',
      'Съемный капюшон с магнитными застёжками',
      'Стропы для носки куртки в помещении',
    ],
    sizes: [{
      name: 'm',
      isAvailable: false,
      description: '168см - 176см',
    },
    {
      name: 'l',
      isAvailable: true,
      description: '176см - 184см',
    },
    {
      name: 'xl',
      isAvailable: true,
      description: '184см - 193см',
    }],
  },
  {
    id: 5,
    profileImg: 'https://m.media-amazon.com/images/I/71gEWlwpN9L._AC_SX569_.jpg',
    title: 'Худи 5',
    price: 7_500_00,
    description: '123123123',
    sizes: [],
  },
]